apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"kuard-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["kuard.example.com"],"po
rt":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2021-06-03T13:58:55Z"
  generation: 1
  name: kuard-gateway
  namespace: default
  resourceVersion: "398700"
  uid: 15500647-2c11-47b7-8333-f1f8c02f4257
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kuard.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
